// Generated by CoffeeScript 1.8.0
var Collection, mongodb, oid, prepare, utils;

utils = require('./utils');

mongodb = require('mongodb');

Collection = (function() {
  function Collection(db, name) {
    this.db = db;
    this.name = name;
  }

  Collection.prototype.oid = function(value) {
    return oid(value);
  };

  Collection.prototype.prepare = function(params) {
    return prepare(params);
  };

  Collection.prototype._find = function(params, options, fn) {
    var _ref;
    _ref = utils.normalize(params, options, fn), params = _ref.params, options = _ref.options, fn = _ref.fn;
    this.db.open(this.name, function(err, col) {
      var cursor, field, fields, _i, _len, _ref1;
      if (err) {
        fn(err, []);
        return;
      }
      fields = {};
      if (options && utils.is.arr(options.fields)) {
        _ref1 = options.fields;
        for (_i = 0, _len = _ref1.length; _i < _len; _i++) {
          field = _ref1[_i];
          if (!utils.is.str(field)) {
            continue;
          }
          fields[field] = 1;
        }
      }
      cursor = col.find(prepare(params), fields);
      if (options) {
        if (options.limit) {
          cursor.limit(options.limit);
        }
        if (options.skip) {
          cursor.skip(options.skip);
        }
        if (options.sort) {
          cursor.sort(options.sort);
        }
      }
      cursor.toArray(function(error, response) {
        if (error) {
          response = [];
        }
        fn(error, response);
      });
    });
  };

  Collection.prototype.find = function(params, options, fn) {
    this._find(params, options, fn);
  };

  Collection.prototype.findOne = function(params, options, fn) {
    var _ref;
    _ref = utils.normalize(params, options, fn), params = _ref.params, options = _ref.options, fn = _ref.fn;
    if (!options) {
      options = {};
    }
    options.limit = 1;
    this._find(params, options, function(error, response) {
      var _ref1;
      response = (_ref1 = response[0]) != null ? _ref1 : false;
      fn(error, response);
    });
  };

  Collection.prototype.findById = function(id, fields, fn) {
    var options, params;
    if (utils.is.fun(fields)) {
      fn = fields;
      fields = null;
    }
    if (!utils.is.fun(fn)) {
      fn = function() {};
    }
    params = {
      _id: id
    };
    options = utils.is.arr(fields) ? {
      fields: fields
    } : {};
    options.limit = 1;
    this._find(params, options, function(error, response) {
      var _ref;
      response = (_ref = response[0]) != null ? _ref : false;
      fn(error, response);
    });
  };

  Collection.prototype.save = function(params, fn) {
    var _ref;
    _ref = utils.normalize(params, fn), params = _ref.params, fn = _ref.fn;
    this.db.open(this.name, function(err, col) {
      if (err) {
        fn(err, []);
        return;
      }
      params = prepare(params);
      col.save(params, function(error, response) {
        if (error) {
          response = false;
        }
        if (response.result.n > 0) {
          if (response.ops != null) {
            response = response.ops.length === 1 ? response.ops[0] : response.ops;
          } else {
            response = params;
          }
        } else {
          response = [];
        }
        fn(error, response);
      });
    });
  };

  Collection.prototype.update = function(params, data, fn) {
    var options, _ref;
    _ref = utils.normalize(params, data, fn), params = _ref.params, options = _ref.options, fn = _ref.fn;
    this.db.open(this.name, function(err, col) {
      if (err) {
        fn(err, false);
        return;
      }
      params = prepare(params);
      data = options;
      options = {
        multi: true,
        upsert: false
      };
      col.update(params, data, options, function(error) {
        var result;
        result = !error;
        fn(error, result);
      });
    });
  };

  Collection.prototype._remove = function(params, fn) {
    var _ref;
    _ref = utils.normalize(params, fn), params = _ref.params, fn = _ref.fn;
    this.db.open(this.name, function(err, col) {
      if (err) {
        fn(err, []);
        return;
      }
      params = prepare(params);
      col.remove(params, function(error, response) {
        if (error) {
          response = false;
        }
        fn(error, response.result.n > 0);
      });
    });
  };

  Collection.prototype.remove = function(params, fn) {
    this._remove(params, fn);
  };

  Collection.prototype.removeById = function(id, fn) {
    this._remove({
      _id: id
    }, fn);
  };

  Collection.prototype.count = function(params, fn) {
    var _ref;
    _ref = utils.normalize(params, fn), params = _ref.params, fn = _ref.fn;
    this.db.open(this.name, function(err, col) {
      if (err) {
        fn(err, []);
        return;
      }
      params = prepare(params);
      col.count(params, function(error, response) {
        if (error) {
          response = false;
        }
        fn(error, parseInt(response, 10) || 0);
      });
    });
  };

  return Collection;

})();

oid = function(value) {
  if (!value) {
    return new mongodb.ObjectID();
  }
  if (utils.is.str(value)) {
    value = new mongodb.ObjectID(value);
  }
  return value;
};

prepare = function(params) {
  var operator;
  if (!params) {
    return null;
  }
  if (!params._id && !params.id) {
    return params;
  }
  if (!params._id && params.id) {
    params._id = params.id;
    delete params.id;
  }
  if (utils.is.obj(params._id)) {
    operator = false;
    if (utils.is.arr(params._id.$in)) {
      operator = '$in';
    }
    if (utils.is.arr(params._id.$nin)) {
      operator = '$nin';
    }
    if (operator) {
      params._id[operator] = params._id[operator].map(function(value) {
        return oid(value);
      });
    }
  } else {
    params._id = oid(params._id);
  }
  return params;
};

module.exports = Collection;
