// Generated by CoffeeScript 1.8.0
var arr, fun, obj, str;

fun = function(f) {
  return typeof f === 'function';
};

str = function(s) {
  return typeof s === 'string';
};

arr = function(a) {
  return a instanceof Array;
};

obj = function(o) {
  return o instanceof Object && !fun(o) && !arr(o);
};

exports.is = {
  fun: fun,
  str: str,
  arr: arr,
  obj: obj
};

exports.normalize = function(params, options, fn) {
  if (fun(params)) {
    fn = params;
    params = null;
    options = null;
  } else if (fun(options)) {
    fn = options;
    options = null;
  }
  if (!fun(fn)) {
    fn = function() {};
  }
  return {
    params: params,
    options: options,
    fn: fn
  };
};
